/*
 * amalgamate.c — emit a single release header from one or more input files.
 *
 * Phase 0: a generic concatenator. When the implementation is later split
 * under src/, list the parts in dependency order to regenerate a single
 * amalgamated header:
 *
 *     amalgamate <output> <input1> [input2 ...]
 *
 * SPDX-License-Identifier: Apache-2.0
 * Copyright 2026 Moritz Angermann <moritz@zw3rk.com>, zw3rk pte. ltd.
 */
#include <stdio.h>

int main(int argc, char **argv){
    FILE *out;
    int i;

    if(argc < 3){
        fprintf(stderr, "usage: %s <output> <input1> [input2 ...]\n", argv[0]);
        return 2;
    }

    out = fopen(argv[1], "wb");
    if(!out){
        perror(argv[1]);
        return 1;
    }

    fputs("/* Auto-generated by tools/amalgamate.c -- do not edit by hand. */\n",
          out);

    for(i = 2; i < argc; i++){
        FILE *in = fopen(argv[i], "rb");
        int c;
        if(!in){
            perror(argv[i]);
            fclose(out);
            return 1;
        }
        while((c = fgetc(in)) != EOF){
            fputc(c, out);
        }
        fclose(in);
    }

    if(fclose(out) != 0){
        perror(argv[1]);
        return 1;
    }
    return 0;
}
