#!/usr/bin/env python3
# Generate tools/vendor/vt_font.h — an 8x16 grayscale bitmap font baked from
# DejaVu Sans Mono (Bitstream Vera / DejaVu license, freely redistributable).
# Regenerate with:  make gen-font   (see Makefile). Do not hand-edit the header.
from PIL import Image, ImageFont, ImageDraw
import glob

CW, CH = 8, 16
# ASCII + a box-drawing / symbol subset the TUI actually uses.
glyphs = [chr(c) for c in range(0x20, 0x7F)]
glyphs += list("─│┌┐└┘├┤┬┴┼═║╔╗╚╝╠╣╦╩╬▒▓█▄▀▐▌●○◦·•↑↓←→…❯■□")

fp = sorted(glob.glob('/nix/store/*dejavu*/share/fonts/truetype/DejaVuSansMono.ttf'))
if not fp:
    raise SystemExit("DejaVuSansMono.ttf not found in the nix store")
font = ImageFont.truetype(fp[0], 13)
ascent, descent = font.getmetrics()

def render(ch):
    img = Image.new('L', (CW, CH), 0)
    d = ImageDraw.Draw(img)
    try:
        w = d.textlength(ch, font=font)
    except Exception:
        w = CW
    x = round((CW - w) / 2.0)
    y = round((CH - (ascent + descent)) / 2.0)
    d.text((x, y), ch, fill=255, font=font)
    return list(img.getdata())

lines = [
    '/* Generated by tools/gen_font.py — 8x16 grayscale font (DejaVu Sans Mono).',
    ' * Do not hand-edit; regenerate with `make gen-font`. */',
    '#ifndef VT_FONT_H',
    '#define VT_FONT_H',
    'enum { VT_FONT_CW = %d, VT_FONT_CH = %d };' % (CW, CH),
    'typedef struct { unsigned int cp; unsigned char cov[%d]; } VtGlyph;' % (CW * CH),
    'static const VtGlyph vt_font[] = {',
]
for ch in glyphs:
    cov = render(ch)
    lines.append('  {0x%04X,{%s}},' % (ord(ch), ','.join(str(v) for v in cov)))
lines += [
    '};',
    'static const int vt_font_n = (int)(sizeof(vt_font)/sizeof(vt_font[0]));',
    '#endif',
    '',
]
open('tools/vendor/vt_font.h', 'w').write('\n'.join(lines))
print('wrote tools/vendor/vt_font.h:', len(glyphs), 'glyphs, cell %dx%d' % (CW, CH))

# sanity: print one glyph as ASCII art
sample = render('A')
print('sample "A":')
for r in range(CH):
    print(''.join('#' if sample[r*CW+c] > 96 else '.' for c in range(CW)))
