#!/usr/bin/env python3
# Subset the four DejaVu Sans Mono styles (regular/bold/oblique/bold-oblique) ->
# tools/vendor/vt_font_ttf.h (four C byte arrays), covering the ranges vt_gif's
# OUTLINE text face needs. vt_gif rasterizes with stb_truetype and picks the
# variant from the cell's bold/italic attributes. Regenerate with `make gen-font-ttf`.
import glob, io
from fontTools.ttLib import TTFont
from fontTools.subset import Subsetter, Options

RANGES = [
    (0x0020, 0x007E), (0x00A0, 0x00FF), (0x0100, 0x017F), (0x0180, 0x024F),
    (0x02B0, 0x02FF), (0x0370, 0x03FF), (0x0400, 0x04FF),
    (0x2000, 0x206F), (0x2190, 0x21FF), (0x2200, 0x22FF),
    (0x2500, 0x257F), (0x2580, 0x259F), (0x25A0, 0x25FF),
    (0x2600, 0x26FF), (0x2700, 0x27BF),
]
unicodes = [cp for a, b in RANGES for cp in range(a, b + 1)]

VARIANTS = [
    ("regular", "DejaVuSansMono.ttf"),
    ("bold",    "DejaVuSansMono-Bold.ttf"),
    ("oblique", "DejaVuSansMono-Oblique.ttf"),
    ("boldob",  "DejaVuSansMono-BoldOblique.ttf"),
]

def subset(fname):
    fp = sorted(glob.glob("/nix/store/*dejavu*/share/fonts/truetype/" + fname))[0]
    opts = Options()
    opts.glyph_names = False
    opts.recalc_bounds = True
    opts.drop_tables += ["GSUB", "GPOS", "GDEF", "kern"]
    font = TTFont(fp)
    s = Subsetter(options=opts)
    s.populate(unicodes=unicodes)
    s.subset(font)
    buf = io.BytesIO(); font.save(buf)
    return buf.getvalue()

with open("tools/vendor/vt_font_ttf.h", "w") as f:
    f.write("/* Generated by tools/gen_font_ttf.py from DejaVu Sans Mono (subset,\n")
    f.write(" * 4 styles). Bitstream Vera / DejaVu license (see tools/vendor/NOTICE).\n")
    f.write(" * Regenerate with `make gen-font-ttf`; do not hand-edit. */\n")
    f.write("#ifndef VT_FONT_TTF_H\n#define VT_FONT_TTF_H\n")
    total = 0
    for name, fname in VARIANTS:
        data = subset(fname); total += len(data)
        f.write("static const unsigned char vt_font_ttf_%s[] = {\n" % name)
        for i in range(0, len(data), 20):
            f.write(" " + "".join("%d," % b for b in data[i:i + 20]) + "\n")
        f.write("};\nstatic const unsigned int vt_font_ttf_%s_len = %du;\n" % (name, len(data)))
        print("  %-8s %d bytes" % (name, len(data)))
    f.write("#endif\n")
print("wrote tools/vendor/vt_font_ttf.h:", total, "bytes total")
