#!/usr/bin/env python3
# Generate tools/vendor/emoji_atlas.h — a curated colour-emoji atlas (codepoint ->
# PNG bytes) from Twemoji (CC-BY 4.0). vt_gif decodes these with stb_image as the
# BUNDLED, reproducible emoji face (--system-emoji prefers the OS font). Add a
# codepoint to CODEPOINTS and rerun `make gen-emoji`. Do not hand-edit the header.
import os, sys, urllib.request

# Curated set: the demo/chat emoji + common ones. Hex codepoint -> filename.
CODEPOINTS = [
    "1f44b", "1f389", "1f680", "1f30d", "1f4f7", "1f44d", "2705", "2764",
    "1f525", "1f600", "1f642", "2b50", "1f4a1", "1f64c", "1f31f", "1f4e6",
    "1f41b", "1f440", "1f9e0", "1f4ac", "26a1", "1f923", "1f4a5", "1f680",
    "1f4a9", "1f680", "2728", "1f44f", "1f647", "1f973",
]
BASE = "https://raw.githubusercontent.com/twitter/twemoji/master/assets/72x72"
LOCAL = "/tmp/twemoji"   # fallback: a pre-fetched dir

def fetch(cp):
    path = os.path.join(LOCAL, cp + ".png")
    if os.path.exists(path):
        return open(path, "rb").read()
    try:
        with urllib.request.urlopen(BASE + "/" + cp + ".png", timeout=15) as r:
            return r.read()
    except Exception as e:
        print("  skip %s: %s" % (cp, e), file=sys.stderr)
        return None

seen, entries, blobs = set(), [], []
for i, cp in enumerate(dict.fromkeys(CODEPOINTS)):   # de-dup, preserve order
    data = fetch(cp)
    if not data or len(data) < 100:
        continue
    idx = len(blobs)
    blobs.append("static const unsigned char emoji_%d[] = {%s};" % (idx, ",".join(str(b) for b in data)))
    entries.append("  {0x%s, emoji_%d, %d}," % (cp.upper(), idx, len(data)))

with open("tools/vendor/emoji_atlas.h", "w") as f:
    f.write("/* Generated by tools/gen_emoji.py from Twemoji (CC-BY 4.0, see NOTICE).\n")
    f.write(" * Curated colour-emoji atlas: codepoint -> PNG bytes; decoded lazily by\n")
    f.write(" * vt_gif with stb_image. Regenerate with `make gen-emoji`; do not edit. */\n")
    f.write("#ifndef EMOJI_ATLAS_H\n#define EMOJI_ATLAS_H\n")
    f.write("\n".join(blobs) + "\n")
    f.write("static const struct { unsigned int cp; const unsigned char *png; int len; } emoji_atlas[] = {\n")
    f.write("\n".join(entries) + "\n};\n")
    f.write("static const int emoji_atlas_n = %d;\n#endif\n" % len(entries))
print("wrote tools/vendor/emoji_atlas.h:", len(entries), "emoji")
