#!/usr/bin/env python3
# Generate tools/vendor/vt_font_cjk.h — a BUNDLED, reproducible CJK bitmap face
# from GNU Unifont's .bdf (16x16 glyphs). Packs the CJK-relevant BMP ranges as
# (cp, 32-byte bitmap) records, deflate-compressed; vt_gif inflates once at start
# (stbi_zlib) and renders them scaled to the cell. Unifont is OFL-1.1.
# Regenerate with `make gen-cjk`; do not hand-edit the header.
import glob, struct, zlib, sys

RANGES = [(0x3000, 0x303F), (0x3040, 0x30FF), (0x3400, 0x4DBF), (0x4E00, 0x9FFF),
          (0xAC00, 0xD7A3), (0xF900, 0xFAFF), (0xFF00, 0xFFEF)]
def inrange(cp): return any(a <= cp <= b for a, b in RANGES)

bdf = glob.glob('/nix/store/*unifont*/share/fonts/unifont.bdf')
if not bdf:
    sys.exit("unifont.bdf not found (nix-shell -p unifont)")

glyphs = {}
cur, rows, reading = None, [], False
for line in open(bdf[0], encoding='latin-1'):
    if line.startswith('ENCODING'):
        cur = int(line.split()[1])
    elif line.startswith('BITMAP'):
        reading, rows = True, []
    elif line.startswith('ENDCHAR'):
        reading = False
        if cur is not None and inrange(cur) and rows:
            packed = bytearray(32)                 # 16 rows x 2 bytes (16-wide)
            for r, h in enumerate(rows[:16]):
                v = int(h, 16)
                if len(h) <= 2:                    # narrow (8-wide) -> left-align
                    v <<= 8
                packed[r*2], packed[r*2+1] = (v >> 8) & 0xFF, v & 0xFF
            glyphs[cur] = bytes(packed)
        cur = None
    elif reading:
        rows.append(line.strip())

blob = bytearray()
for cp in sorted(glyphs):                          # sorted -> binary search at runtime
    blob += struct.pack('<I', cp) + glyphs[cp]
comp = zlib.compress(bytes(blob), 9)

with open('tools/vendor/vt_font_cjk.h', 'w') as f:
    f.write('/* Generated by tools/gen_cjk.py from GNU Unifont .bdf (OFL-1.1, see\n')
    f.write(' * NOTICE). Deflate-compressed (cp,16x16 bitmap) records; vt_gif inflates\n')
    f.write(' * once with stbi_zlib. Regenerate with `make gen-cjk`; do not edit. */\n')
    f.write('#ifndef VT_FONT_CJK_H\n#define VT_FONT_CJK_H\n')
    f.write('enum { VT_CJK_COUNT = %d, VT_CJK_RAW = %d };\n' % (len(glyphs), len(blob)))
    f.write('static const unsigned char vt_font_cjk_z[] = {\n')
    for i in range(0, len(comp), 20):
        f.write(' ' + ''.join('%d,' % b for b in comp[i:i+20]) + '\n')
    f.write('};\nstatic const int vt_font_cjk_zlen = %d;\n#endif\n' % len(comp))
print('wrote tools/vendor/vt_font_cjk.h:', len(glyphs), 'glyphs,',
      len(comp)//1024, 'KB compressed (', len(blob)//1024, 'KB raw )')
